# Generated by Django 5.1.7 on 2025-04-03 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('refrigeration_mode', models.IntegerField(null=True)),
                ('is_not_topologed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=45)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('is_fixing', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=45, null=True)),
                ('is_requiring_verification', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'DocumentTypes',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('code', models.CharField(max_length=45, unique=True)),
                ('address', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.warehouse')),
            ],
            options={
                'verbose_name_plural': 'AppUsers',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45)),
                ('total_quantity', models.IntegerField(null=True)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('post_barcode', models.CharField(max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('required_at', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=45, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_creator', to='wmsprototype.appuser')),
                ('linked_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.document')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_verifier', to='wmsprototype.appuser')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.documenttype')),
                ('destination_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_warehouse', to='wmsprototype.warehouse')),
                ('original_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_warehouse', to='wmsprototype.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('barcode', models.CharField(max_length=45, null=True)),
                ('type', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.level')),
            ],
            options={
                'verbose_name_plural': 'Cells',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('ean', models.CharField(max_length=13, null=True, unique=True)),
                ('sku', models.CharField(max_length=45)),
                ('image', models.ImageField(null=True, upload_to='products/')),
                ('description', models.CharField(max_length=45, null=True)),
                ('package_max_quantity', models.IntegerField(null=True)),
                ('package_of_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.product')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(null=True)),
                ('serial', models.CharField(max_length=45, null=True)),
                ('quantity_in_package', models.IntegerField()),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('moved_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.cell')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.product')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Document_has_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_added', models.IntegerField()),
                ('amount_required', models.IntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.product')),
            ],
            options={
                'verbose_name_plural': 'Documents_has_Products',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.department')),
            ],
            options={
                'verbose_name_plural': 'Rows',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.row')),
            ],
            options={
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.section'),
        ),
    ]
