# Generated by Django 5.1.7 on 2025-04-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsprototype', '0002_doctypes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='number',
            new_name='document_number',
        ),
        migrations.AlterField(
            model_name='document',
            name='current_status',
            field=models.CharField(default='Created', max_length=45),
        ),
    ]
