# Generated by Django 5.1.7 on 2025-03-23 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsprototype', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents_has_Products',
            new_name='Document_has_Product',
        ),
        migrations.AlterModelOptions(
            name='cell',
            options={'verbose_name_plural': 'Cells'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='document_has_product',
            options={'verbose_name_plural': 'Documents_has_Products'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name_plural': 'DocumentTypes'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'verbose_name_plural': 'Rows'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AddField(
            model_name='department',
            name='is_not_topologed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.warehouse')),
            ],
            options={
                'verbose_name_plural': 'AppUsers',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_creator', to='wmsprototype.appuser'),
        ),
        migrations.AlterField(
            model_name='document',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_verifier', to='wmsprototype.appuser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.appuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
