# Generated by Django 5.1.7 on 2025-04-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsprototype', '0003_rename_number_document_document_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_in_package',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_max_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_of_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='scu',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='current_status',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='documentproduct',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='checked_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='moved_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='placed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
