# Generated by Django 5.1.7 on 2025-03-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsprototype', '0003_rename_documents_has_products_document_has_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
