# Generated by Django 5.1.7 on 2025-04-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmsprototype', '0004_final_polyshing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentproduct',
            unique_together=set(),
        ),
    ]
