# Generated by Django 5.1.7 on 2025-03-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsprototype', '0004_alter_appuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='scu',
            new_name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='document_has_product',
            name='amount_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
