# Generated by Django 5.1.7 on 2025-03-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsprototype', '0005_rename_scu_product_sku_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='refrigeration_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
