# Generated by Django 5.1.7 on 2025-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsprototype', '0006_alter_department_refrigeration_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='number',
            field=models.IntegerField(),
        ),
    ]
