# Generated by Django 5.1.7 on 2025-04-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsprototype', '0006_add_bakery_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='level',
            field=models.ForeignKey(db_column='level_id', on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.level'),
        ),
        migrations.AlterField(
            model_name='department',
            name='default_cell',
            field=models.ForeignKey(blank=True, db_column='default_cell_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_department_of', to='wmsprototype.cell'),
        ),
        migrations.AlterField(
            model_name='level',
            name='section',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.section'),
        ),
        migrations.AlterField(
            model_name='row',
            name='department',
            field=models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.department'),
        ),
        migrations.AlterField(
            model_name='section',
            name='row',
            field=models.ForeignKey(db_column='row_id', on_delete=django.db.models.deletion.CASCADE, to='wmsprototype.row'),
        ),
    ]
